apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-service
  labels:
    app: msg-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msg-service
  template:
    metadata:
      labels:
        app: msg-service
    spec:
      hostname: msg-service
      containers:
      - name: msg-service
        image: msg-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi
