apiVersion: v1
kind: Service
metadata:
  name: msg-service
  labels:
    app: msg-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30048
  selector:
    app: msg-service